# Generated by Django 2.0.6 on 2018-11-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_management', '0002_auto_20181101_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimarEsforco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=100, verbose_name='Atividade')),
                ('tempo_esfoco', models.IntegerField(verbose_name='Tempo de esforço')),
                ('profissional', models.CharField(max_length=100, verbose_name='Perfil do Profissional')),
                ('esforco_total', models.IntegerField(verbose_name='Esfoço Total')),
            ],
        ),
        migrations.RenameModel(
            old_name='Login',
            new_name='MeuLogin',
        ),
        migrations.RemoveField(
            model_name='cadastroos',
            name='esforco_estimado',
        ),
        migrations.RemoveField(
            model_name='cadastroos',
            name='esforco_realizado',
        ),
        migrations.RemoveField(
            model_name='cadastroos',
            name='esforco_relacionamento',
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='processo_adm',
            field=models.CharField(max_length=20, verbose_name='Processo Administrativo'),
        ),
        migrations.AlterField(
            model_name='cadastroos',
            name='processo_adm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Administrativo'),
        ),
        migrations.AlterField(
            model_name='cadastroos',
            name='responsavel',
            field=models.CharField(max_length=100, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
