# Generated by Django 2.0.6 on 2018-10-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_os', models.IntegerField()),
                ('responsavel', models.CharField(max_length=100)),
                ('prioridade', models.BooleanField(default=False, verbose_name='Emergencial')),
                ('data_necessidade', models.DateField(verbose_name='Data da necessidade')),
                ('solicitacao', models.TextField(max_length=1500, verbose_name='Solicitação')),
                ('esforco_estimado', models.IntegerField(verbose_name='Esforço estimado')),
                ('esforco_realizado', models.IntegerField(verbose_name='Esforço realizado')),
                ('esforco_relacionamento', models.IntegerField(verbose_name='Esforço Relacionamento')),
                ('data_entrega', models.DateField(verbose_name='Data de entrega')),
                ('data_aceite', models.DateField(verbose_name='Data de aceite')),
                ('ss_prestador_servico', models.CharField(max_length=10)),
                ('mes_fatura', models.CharField(max_length=10, verbose_name='Mês fatura')),
                ('ano_fatura', models.IntegerField()),
                ('observacao', models.TextField(max_length=500, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandante', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisao_sigla', models.CharField(max_length=6)),
                ('divisao_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atendente', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentacao', models.CharField(max_length=100)),
                ('data_movimentacao', models.DateField()),
                ('n_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.CadastroOS')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_contrato_aditivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TermoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_contrato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CORRECAO', 'Correção'), ('EVOLUCAO', 'Evolução')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_login', models.CharField(max_length=10)),
                ('usuario_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='demandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Demandante'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Sistema'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='termo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TermoContrato'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='termo_contrato_aditivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TermoAditivo'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TipoServico'),
        ),
    ]
