# Generated by Django 2.0.6 on 2018-11-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo_adm', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='fase',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='os_management.Fase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='status',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='os_management.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastroos',
            name='termo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TermoContrato', verbose_name='Termo de Contrato'),
        ),
        migrations.AlterField(
            model_name='cadastroos',
            name='termo_contrato_aditivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TermoAditivo', verbose_name='Termo Aditivo de Contrato'),
        ),
        migrations.AlterField(
            model_name='cadastroos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TipoServico', verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='processo_adm',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='os_management.Administrativo', verbose_name='Processo Administrativo'),
            preserve_default=False,
        ),
    ]
