# Generated by Django 2.0.9 on 2018-10-10 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('os_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_processo_adm', models.IntegerField(primary_key=True, serialize=False)),
                ('processo_adm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroOS',
            fields=[
                ('n_os', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('dt_necessidade', models.DateField()),
                ('solicitacao', models.TextField(max_length=100)),
                ('esforco_estimado', models.IntegerField()),
                ('esforco_realizado', models.IntegerField()),
                ('esforco_relacionamento', models.IntegerField()),
                ('dt_entrega', models.DateField()),
                ('dt_aceite', models.DateField()),
                ('ss_prestador_servico', models.CharField(max_length=10)),
                ('mes_fatura', models.CharField(max_length=10)),
                ('ano_fatura', models.IntegerField()),
                ('observacao', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id_area_demandante', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Divisao')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_fase', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_atendente', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=12)),
                ('senha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentacao', models.CharField(max_length=100)),
                ('dt_movimentacao', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Usuario')),
                ('n_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.CadastroOS')),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id_prioridade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prioridade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sistema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id_termo_contrato_ad', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('termo_contrato_aditivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TermoContrato',
            fields=[
                ('id_termo_contrato', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('termo_contrato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id_tipo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='id_demandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Demandante'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='id_prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Prioridade'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='id_processo_adm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Administrativo'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='id_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.Sistema'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='id_termo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TermoContrato'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TipoServico'),
        ),
        migrations.AddField(
            model_name='cadastroos',
            name='termo_aditivo_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_management.TermoAditivo'),
        ),
    ]
