# Generated by Django 2.0.6 on 2019-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_management', '0003_auto_20181130_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandante',
            name='nome_demandante',
            field=models.CharField(default=0.08333333333333333, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastroos',
            name='data_necessidade',
            field=models.DateField(max_length=8, verbose_name='Data da necessidade'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
