# Generated by Django 2.1.1 on 2018-10-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordenadorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id_divisao', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=6)),
                ('nome_divisao', models.CharField(max_length=100)),
                ('id_coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenadorias.Coordenadoria')),
            ],
        ),
    ]
