# Generated by Django 2.1.1 on 2018-10-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=10)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('id_divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisoes.Divisao')),
            ],
        ),
    ]
