# Generated by Django 2.1.1 on 2018-10-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandante', '0001_initial'),
        ('fase', '0001_initial'),
        ('prioridade', '0001_initial'),
        ('contrato', '0001_initial'),
        ('sistema', '0001_initial'),
        ('administrativo', '0001_initial'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('n_os', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_emissao', models.DateField()),
                ('responsavel', models.CharField(max_length=100)),
                ('dt_nece', models.DateField()),
                ('solicitacao', models.TextField(max_length=100)),
                ('estima_esforco', models.IntegerField()),
                ('reali_esforco', models.IntegerField()),
                ('esforco_relacio', models.IntegerField()),
                ('dt_entrega', models.DateField()),
                ('dt_aceite', models.DateField()),
                ('ss_presta_serv', models.CharField(max_length=10)),
                ('mes_fatura', models.CharField(max_length=10)),
                ('ano_fatura', models.IntegerField()),
                ('obs', models.TextField(max_length=100)),
                ('id_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandante.Demandante')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fase.Fase')),
                ('id_priori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prioridade.Prioridade')),
                ('id_processo_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Administrativo')),
                ('id_sist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Sistema')),
                ('id_termo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.TermoContrato')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo.Tipo_Serv')),
                ('termo_aditivo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.TermoAditivo')),
            ],
        ),
    ]
