# Generated by Django 2.1.1 on 2018-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id_processo_adm', models.IntegerField(primary_key=True, serialize=False)),
                ('processo_adm', models.CharField(max_length=20)),
            ],
        ),
    ]
