# Generated by Django 2.1.1 on 2018-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id_termo_contrato_ad', models.IntegerField(primary_key=True, serialize=False)),
                ('termo_aditivo_contrato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TermoContrato',
            fields=[
                ('id_termo_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('termo_contrato', models.CharField(max_length=20)),
            ],
        ),
    ]
